<a href="https://colab.research.google.com/github/TU24007/EU_M_Math/blob/main/Chap05_Ex-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [4]:
sample_array = np.arange(10)
print('sample_array',sample_array)

sample_array [0 1 2 3 4 5 6 7 8 9]


In [6]:
sample_array_slice =sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4]


In [7]:
sample_array_slice[0:3]=10
print(sample_array_slice)

[10 10 10  3  4]


In [8]:
sample_array_copy =np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3]=20
print(sample_array_copy)

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [11]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [12]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [13]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [14]:
cond_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])

y_array = np.array([100,200,300,400,500])

print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


In [15]:
#bのデータ 5-1
data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [19]:
#c以外のデータ 5-2
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [20]:
#5-3
cond_data=np.array([False,False,True,True,False])
x_array=np.array([1,2,3,4,5])
y_array=np.array([6,7,8,9,10])
print(np.where(cond_data,x_array,y_array))

[ 6  7  3  4 10]
