<a href="https://colab.research.google.com/github/TU24007/EU_M_Math/blob/main/Chap05_Ex_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [ ]:
sample_array=np.arange(10)
sample_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_array2 =sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
sample_array3=np.array([[1,2,3],[4,5,6]])
sample_array4=np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3,sample_array4],axis=0)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.vstack((sample_array3,sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([sample_array3,sample_array4],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.hstack((sample_array3,sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
sample_array3=np.array([[1,2,3],[4,5,6]])
sample_array4=np.array([[7,8,9],[10,11,12]])
sample_array_vstack=np.vstack((sample_array3,sample_array4))

sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
first,second,third=np.split(sample_array_vstack,[1,3])

print(first)

[[1 2 3]]


In [ ]:
print(second)

[[4 5 6]
 [7 8 9]]


In [ ]:
second[0]

array([4, 5, 6])

In [ ]:
print(third)

[[10 11 12]]


In [ ]:
sample_array5=np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2=np.vstack((sample_array3,sample_array4,sample_array5))

print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [ ]:
first,second,third,fourth=np.split(sample_array_vstack2,[2,3,5])
print('・1つ目:\n',first,'\n')
print('・2つ目:\n',second,'\n')
print('・3つ目:\n',third,'\n')
print('・4つ目:\n',fourth,'\n')

・1つ目:
 [[1 2 3]
 [4 5 6]] 

・2つ目:
 [[7 8 9]] 

・3つ目:
 [[10 11 12]
 [13 14 15]] 

・4つ目:
 [[16 17 18]
 [19 20 21]] 



In [ ]:
first[0]

array([1, 2, 3])

In [ ]:
first[1]

array([4, 5, 6])

In [ ]:
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [ ]:
sample_array=np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
sample_array +3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#5-7
sample_array1=np.arange(12).reshape(3,4)
sample_array2=np.arange(12).reshape(3,4)

np.vstack((sample_array1,sample_array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#5-8
np.hstack((sample_array1,sample_array2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
#5-9
sample_list=np.array([1,2,3,4,5])
sample_list + 3

array([4, 5, 6, 7, 8])