<a href="https://colab.research.google.com/github/TU24007/EU_M_Math/blob/main/Chap05_Ex-02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
cond_data=np.array([True,True,False,False,True])

print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [3]:
sample_data=np.arange(10)
print('元のデータ:',sample_data)
print('すべての要素の平方根:',np.sqrt(sample_data))
print('すべての要素のネイビア指数関数:',np.exp(sample_data))

元のデータ: [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根: [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイビア指数関数: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [4]:
sample_multi_array_data1=np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print('最小値:',sample_multi_array_data1.min())
print('最大値:',sample_multi_array_data1.max())
print('平均値:',sample_multi_array_data1.mean())
print('合計:',sample_multi_array_data1.sum())

print('行の合計:',sample_multi_array_data1.sum(axis=1))
print('列の合計:',sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値: 0
最大値: 8
平均値: 4.0
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


In [6]:
coda_data=np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか:',cond_data.any())
print('すべてTrueかどうか:',cond_data.all())

Trueが少なくとも1つあるかどうか: True
すべてTrueかどうか: False


In [7]:
sample_multi_array_data1 =np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print('5より大きい数字がいくつあるか:',(sample_multi_array_data1>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか: 3


In [8]:
sample_multi_array_data1=np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分:',np.diag(sample_multi_array_data1))
print('対角成分の和:',np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分: [0 4 8]
対角成分の和: 12


In [11]:
#5-4

sample_multi_array_data2=np.arange(16).reshape(4,4)
sample_multi_array_data2

print('平方根を計算した行列:',np.sqrt(sample_multi_array_data2))

平方根を計算した行列: [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [12]:
#5-5

print('最小値:',sample_multi_array_data2.min())
print('最大値:',sample_multi_array_data2.max())
print('平均値:',sample_multi_array_data2.mean())
print('合計:',sample_multi_array_data2.sum())

最小値: 0
最大値: 15
平均値: 7.5
合計: 120


In [13]:
#5-6

print('対角成分の和:',np.trace(sample_multi_array_data2))

対角成分の和: 30
